### ISSUE TITLE
Error with 'popular', 'freshest' and 'unsorted' pages

### ISSUE THREAD

**Issue by elaye** [atduskgreg/ofxaddons.com#112]
Hi!
I have the following error most of the time when I go to the `Popular`, `Freshest` and `Unsorted` pages:

                        We're sorry, but something went wrong.
    --------------------------------------------------------------------------------------
    If you are the application owner check the logs for more information.

What do the logs say?

**Comment by jamezilla** [comment]
Here's the relevant logs:

```
Mar 19 11:40:29 ofxaddons-cedar app/web.1:  App 129 stdout: AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".): 
Mar 19 11:40:29 ofxaddons-cedar app/web.1:  App 129 stdout:   app/controllers/addons_controller.rb:22:in `index' 
```
All of those pages are using the same code path, so it's not surprising all three would break if there's an issue. Here's the relevant code:
https://github.com/atduskgreg/ofxaddons.com/blob/master/app/controllers/addons_controller.rb

I have no idea what's going on here. As you can see there's only one render call in that entire controller. It looks like it's a cache issue. If you append some random junk onto the url you can bypass the cache, and, at least, right now the page appears to work fine:

http://www.ofxaddons.com/popular?potato=true

Caches... arg! I won't be able to look at it right away, but thanks for the report.

**Comment by jamezilla** [comment]
Figured it out. It's breaking since the controller is not using a default view. fresh_when sets the response headers, so it's sort of like a call to render.

From the rails api docs:
```
When rendering a different template than the default controller/action style, you can indicate which digest to include in the ETag:

before_action { fresh_when @article, template: 'widgets/show' }
```

That's why the categories and contributor pages don't have a problem - they use the default view.

This has been broken for weeks! Thanks for bringing it to my attention.
