### ISSUE TITLE
Feature Request: geometry category

### ISSUE THREAD

**Issue by AmnonOwed** [atduskgreg/ofxaddons.com#113]
I am sorely missing a **geometry** category on ofxaddons.com. For a creative coding framework such as openFrameworks, one would think that geometry related code is used a lot and this code might become a suitable candidate for an ofxaddon. I've searched through the addons and it seems the following addons might be suitable to be filed under - and thus more easily found via - such a category:

- ofxGeometry
- ofxOpenGP
- ofxOpenMesh
- ofxGLMesh
- ofxHalfEdgeMesh
- ofxMesh
- ofxMeshUtils
- ofxPolyvox
- ofxRules
- ofxTriangleMesh
- ofxMathMesh
- ofxCGAL
- ofxClipper
- ofxMarchingCubes
- ofxPolygonHitTest
- ofxVoro
- ofxVoronoi
- ofxVoronoi2D
- ofxVTerrain

Would it be possible to add a geometry category into the mix?

**Comment by jamezilla** [comment]
Sounds good to me. I'll try to whip this up this in the next few days - we
don't have a category editor at the moment! It's an easy task, just haven't
gotten around to it.

**Comment by AmnonOwed** [comment]
Cool!

I found a few other addons that are also suitable for this category:

- ofxButterfly
- ofxCarveCSG
- ofxCSG

**Comment by AmnonOwed** [comment]
Thanks!

Don't have additional suggestions at the moment.
