### ISSUE TITLE
Stars on addons are not properly calculated!

### ISSUE THREAD

**Issue by rezaali** [atduskgreg/ofxaddons.com#118]
ofxUI has 480 stars, but on ofxaddons it has 0, what gives?

**Comment by jamezilla** [comment]
We just display whatever we get back from the Github API. I manually triggered a refresh for your addon and your numbers popped back up to 480. Maybe a temporary failure on Github's side?

I kicked off a fresh import to hopefully heal any bad data we might have picked up in the update last night.

**Comment by rezaali** [comment]
@jamezilla thanks!
