### ISSUE TITLE
can't get a list of all repos through the api?

### ISSUE THREAD

**Issue by jedahan** [atduskgreg/ofxaddons.com#122]
http://www.ofxaddons.com/api/v1/repos/all.json returns an empty array. Should I be using another endpoint to get the repos?

**Comment by jamezilla** [comment]
Here's the endpoint for all repos:
http://www.ofxaddons.com/api/v1/repos

The reason /repos/all.json is returning an empty array is because it's trying to resolve to a repo named 'all', which doesn't exist. How did you get to that URL? If that's documented somewhere it's old and should be updated.

**Comment by jedahan** [comment]
Seems like I am getting application crashes with that endpoint?

**Comment by jamezilla** [comment]
It's just heroku timing out. It'll eventually work, and then be cached until the next crawl. This will be fully addressed by the planned move to RackSpace.

I'm sure there's some API work to be done here, too. We should probably add some paging. I'll open a separate ticket to track that.

**Comment by jamezilla** [comment]
Closing this as "won't fix".
API changes are in a new ticket #128
