### ISSUE TITLE
No access to ofxaddons-cedar when importing production db

### ISSUE THREAD

**Issue by jedahan** [atduskgreg/ofxaddons.com#123]
I wanna import the production db, but I get this error:

```bash
~/c/ofxaddons.com ❯❯❯ heroku pg:pull DATABASE_URL ofxaddons --app ofxaddons-cedar
 !    You do not have access to the app ofxaddons-cedar.
```

**Comment by jamezilla** [comment]
That's right, you can't just connect to the production DB and suck everything down. That would be a security problem. There's sensitive user info in there.

If I get some free time, I'll try to dump a sanitized version of the production database and put it somewhere for you to download. I'm a bit busy at the moment, though.

**Comment by jedahan** [comment]
Ahh so maybe this should be removed from the readme then?

**Comment by jamezilla** [comment]
The readme is there for core developers as much as for public consumption. I'll add a warning in there that you need to currently access to the heroku instance for that option to work.

**Comment by jedahan** [comment]
Fixed in https://github.com/atduskgreg/ofxaddons.com/commit/7b4877f2935c2e132e6fa039151309d8c72974cc
