### ISSUE TITLE
postgresql documentation

### ISSUE THREAD

**Issue by jedahan** [atduskgreg/ofxaddons.com#124]
Is there a step in between installing postgresql (via homebrew), and `rake db:migrate`?

I have not used postgresql before...

```bash
~/c/ofxaddons.com ❯❯❯ rake db:setup                                                master ✱
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by jedahan** [comment]
ok, I did:

```bash
launchctl load `brew ls postgresql | grep plist`
```

should this be added to the readme?

**Comment by jamezilla** [comment]
Homebrew spits out instructions for getting the daemon running after you install it. Additionally, you can see this information with `brew info postgresql`. 

Hopefully this didn't trip you up too much, but general rails/postgres documentation is out of the scope of this project - it's just a huge topic.
