### ISSUE TITLE
Importer.new.run not outputting anything

### ISSUE THREAD

**Issue by jedahan** [atduskgreg/ofxaddons.com#129]
I am not sure how long this should take, or if it is doing anything at all, when I run:

    rails r 'Importer.new.run(no_cache: true)'

Would be nice to have some sort of output, if possible, even if its just a spinner...

**Comment by jamezilla** [comment]
All the output is going to the rails logs. If it spewed to stdout, it would pollute the system logs since it's running as a cron job.

If you need to monitor:
`tail -f logs/development.log`

Beware... tons of colorful spew.
