### ISSUE TITLE
Addon missing

### ISSUE THREAD

**Issue by edap** [atduskgreg/ofxaddons.com#133]
Hi, I've finished 2 addons ~1 week ago but i can not find them in ofxaddons.com.
https://github.com/edap/ofxLSystem
https://github.com/edap/ofxLSystemGrammar

I've added the examples, the thumbnails and what is described in the faq page.
Also, I find pretty unclear how to contact you, in the website there is this sentence "Feel free to send us a note if you want to tell us about it". But it is not clear to me to who that "us" refers to, or if there is a formular.

**Comment by jamezilla** [comment]
Sorry @edap, I just moved the site between servers and the importer is not running regularly yet. I'll try to get to it in the next week or so. Thanks for your patience.

I appreciate the feedback about the contact prompt on the web site. I've been pretty focused on backend stuff in my limited time, but the front-end will get some love pretty soon. I'll open a separate issue to track it.

**Comment by jamezilla** [comment]
Contact issue being tracked here: #134

**Comment by edap** [comment]
no worries, i just want to make it present ;) Thank you for your work on ofxaddons.com

**Comment by edap** [comment]
One addon is now, listed http://ofxaddons.com/contributors/edap, but the other one no. Could you please point me out the file in this repo that is responsible of the search on github? Maybe I can have a look on what's wrong with the script, or what is missing in my addon. Thanks in advance

**Comment by jamezilla** [comment]
Found it. It had been picked up by the importer, but a moderator flagged it as "Incomplete" so it was hidden from the categorization tool. We need a better system for re-reviewing incomplete addons.
