### ISSUE TITLE
ofxPidee for Hardware Interface category

### ISSUE THREAD

**Issue by rc1** [atduskgreg/ofxaddons.com#136]
Hello.

We have developed a board for the Raspberry Pi, called a [Pidee](http://github.com/pidee), and created an OFX addon called `ofxPidee`. It's a simple little board. Just 3 LEDs, a switch and button. More info here: http://theworkers.net/pidee.

If it's possible to have it in the Hardware Interface category this would help our users out a lot. 

Cheers. Ross

**Comment by jamezilla** [comment]
Sorry, I did this a while ago. You're under the Hardware Interface category. Cool project!
