### ISSUE TITLE
Request for adding two addons.

### ISSUE THREAD

**Issue by HalfdanJ** [atduskgreg/ofxaddons.com#138]
I've relased halfdanj/ofxAndroidMobileVision and halfdanj/ofxFaceTracker2, could they be added to site?

**Comment by jamezilla** [comment]
Hi Jonas! Done. I added them both to the Computer Vision category. Maybe I should make an Android category?

It looks like the thumbnail for the AndoidMobileVision addons is a bit big, so it's rendering funny. Should be 270x70.
