### ISSUE TITLE
ofxKuZed  - addon for working with Stereolab ZED camera

### ISSUE THREAD

**Issue by perevalovds** [atduskgreg/ofxaddons.com#140]
ofxKuZed  - addon for working with Stereolab ZED camera,

Link to addon: https://github.com/kuflex/ofxKuZed

Works in openFrameworks 0.9.3, Windows

Addon falls into the following categories: 
* Hardware interface
* Video/camera

Addons contains example and detailed explanation on requirements, and thumbnail ofxaddons_thumbnail.png

Please, see details in addon's README.

**Comment by jamezilla** [comment]
Done! Thanks for contributing.
