### ISSUE TITLE
ofxGem : share pixies between of and Puredata

### ISSUE THREAD

**Issue by avilleret** [atduskgreg/ofxaddons.com#141]
Hi,

I just want to tell you that I made an ofxGem addon that let you share pixies between of and Puredata/GEM.
I uses OS's shared memory to write / read pixel data from Gem or openFrameworks.
It has been tested on Linux only for now, but it should work on Mac OS X and it might work on Windows too (with some modifications).
Of course, this also allow to share pixies between 2 openframeworks applications.
Code and examples are available here : https://github.com/avilleret/ofxGem
Is it possible to display it on ofxaddons.com ?
Thanks !

**Comment by jamezilla** [comment]
I added it to the "Bridges" and "Utilities" categories. Does that seem appropriate?

**Comment by avilleret** [comment]
Thanks, could you also add it to "Video" categorie since its main purpose it to share pixels between process ?

**Comment by jamezilla** [comment]
You got it. Done.
