### ISSUE TITLE
I have done an addon on call ofxSiri...

### ISSUE THREAD

**Issue by Loongint** [atduskgreg/ofxaddons.com#143]
It's my first time to try to make an addon... So do u thing it's helpful of my addon :)

**Comment by jamezilla** [comment]
@Loongint Don't be shy about submitting your addon. We'll pretty much add anything to the site as long as it conforms to the guide: http://ofxaddons.com/pages/howto#make

I checked the github crawler and didn't see your addon in there, so also make sure your repository is uploaded to github. If it already is, send me a link so I can investigate why it isn't being picked up by the crawler.

**Comment by Loongint** [comment]
http://github.com/loongint/ofxSiri ,thx

**Comment by jamezilla** [comment]
I put it in the "bridges" and "sound" categories. Does that seem right to you?
