### ISSUE TITLE
ofxPortSF

### ISSUE THREAD

**Issue by aaronaanderson** [atduskgreg/ofxaddons.com#144]
Hello! 

I've made an addon, ofxPortSF, to aid in loading, recording, and saving sounds while using the sound stream explicitly. It comes with examples of loading a sound file, recording a sound file in real time, and saving a sound file. It is best suited for the sound category. 

Many thanks!

Aaron

**Comment by jamezilla** [comment]
@aaronaanderson I'm not seeing your addon in the index, so I'll have to investigate why it's not being picked up by the crawler. I'm a bit busy at the moment, so I appreciate your patience - I'll get to it!

**Comment by aaronaanderson** [comment]
@jamezilla , 

No hurry, and I appreciate you spending your time! I am planning on using this in a tutorial series I'm working on dealing with audio in openFrameworks, but I won't need it until the 7th or 8th installment. So take your time! 

Thanks again, 


Aaron

**Comment by jamezilla** [comment]
All set. Thanks for your patience.
