### ISSUE TITLE
ofxKuTextGui - addon for creating textual GUI controlled by keyboard

### ISSUE THREAD

**Issue by perevalovds** [atduskgreg/ofxaddons.com#145]
ofxKuTextGui - addon for creating textual GUI controlled by keyboard

Link to addon: https://github.com/perevalovds/ofxKuTextGui

Works in openFrameworks 0.9.3, OSX, Windows, Linux

Addon falls into the following categories:
    GUI

Addons contains example and thumbnail ofxaddons_thumbnail.png
Readme.md contains link to youtube demo video.

**Comment by jamezilla** [comment]
Added, thanks!
