### ISSUE TITLE
ofxJoystick

### ISSUE THREAD

**Issue by Lacty** [atduskgreg/ofxaddons.com#146]
ofxJoystick --> Simple Gamepad library
addon link ---> https://github.com/Lacty/ofxJoystick
environment -> openFrameworks **0.9.6** and **0.9.7**
--------------> OSX and Windows
readme.md --> usage, contact and lisence(MIT)

**Comment by jamezilla** [comment]
Added to the 'Hardware Interface' category, thanks!
