### ISSUE TITLE
ofxRotationSensing

### ISSUE THREAD

**Issue by sticknor** [atduskgreg/ofxaddons.com#147]
ofxRotationSensing:
This addon features a class that can determine the rotational velocity of a vector when given it's position relative to the center of a circle. When used in conjunction with optical flow, it can be useful for projects in need of rotation sensing from a live feed or recorded video.

Link: https://github.com/sticknor/ofxRotationSensing

Should be categorized with Computer Vision.

**Comment by jamezilla** [comment]
Sorry, I guess this issue didn't closed. It's been added for a while now.
