### ISSUE TITLE
ofxKeyboard

### ISSUE THREAD

**Issue by Lacty** [atduskgreg/ofxaddons.com#149]
ofxJoystick --> Simple Keyboard Input library for Game Developer
addon link ---> https://github.com/Lacty/ofxKeyboard
environment -> openFrameworks **0.9.7**
readme.md --> usage, contact and lisence(MIT)

**Comment by jamezilla** [comment]
Added to the 'Utilities' category. Does that seem right?

**Comment by Lacty** [comment]
Thank, It OK(´・ω・｀)
