### ISSUE TITLE
ofxAsyncTransfer

### ISSUE THREAD

**Issue by shotamatsuda** [atduskgreg/ofxaddons.com#155]
Addon for asynchronous pixel transfers using Pixel Buffer Objects for techniques like streaming texture uploads and asynchronous read-back.

URL: https://github.com/shotamatsuda/ofxAsyncTransfer

**Comment by jamezilla** [comment]
I added this to `Graphics` and `Video/Cameras`. Does that seem right?

**Comment by shotamatsuda** [comment]
Looks good. Thanks a lot!
