### ISSUE TITLE
ofxHPVPlayer

### ISSUE THREAD

**Issue by vjacob** [atduskgreg/ofxaddons.com#158]
Cross platform plugin for playing high-res/high-fps HPV video files (High Performance Video) files.

Url: [https://github.com/vjacob/ofxHPVPlayer](https://github.com/vjacob/ofxHPVPlayer)
Category: Video

Link contains lengthy description and several examples demonstrating its functionality.

**Comment by vjacob** [comment]
anybody?

**Comment by jamezilla** [comment]
Added, thanks for your patience.

**Comment by vjacob** [comment]
Great, thanks!
