### ISSUE TITLE
ofxSiliconRetina

### ISSUE THREAD

**Issue by federicohyo** [atduskgreg/ofxaddons.com#162]
I would like to submit an addon https://github.com/federicohyo/ofxSiliconRetina. This addon is intended for interfacing the neuromorphic vision sensors developed by inilabs.com. These cameras, unlike conventional cameras, do not produce frames but detect contrast changes in light luminosity and emit digital pulses (i.e. spikes, like the human retina). These cameras are extremely fast (equivalent to 6500 frames per second cameras), have high-dynamic range (>120dB), and can achieve very low-latency (<10us). In any case, I would like to advertise the addon in your website. 

Ideally, this addon should show up in the category "video-camera" and "hardware-interface".

thank you for reviewing my request!

**Comment by jamezilla** [comment]
Apologies for the delay. You're all set. Thanks for the contribution!
