### ISSUE TITLE
ofxHoedown

### ISSUE THREAD

**Issue by OMGROFL** [atduskgreg/ofxaddons.com#163]
Standards compliant, fast, secure markdown processing addon for openFrameworks.

A package and examples around Hoedown which is a revived fork of Sundown, the Markdown parser based on the original code of the Upskirt library by Natacha Porté.

URL: https://github.com/PiTube/ofxHoedown
Category: Utilities

**Comment by jamezilla** [comment]
All set. Thanks for the contribution!
