### ISSUE TITLE
ofxDmx4All

### ISSUE THREAD

**Issue by ImanolGo** [atduskgreg/ofxaddons.com#164]
Hi OF community,

I just uploaded a wrapper for USB DMX interfaces "Dmx4All" (dmx4all.eu).

https://github.com/ImanolGo/ofxDmx4All

It is based on the ofxDmx but just to interface with Dmx4All interfaces and I would put it in the Hardware Interface category.

Enjoy it!

**Comment by jamezilla** [comment]
All set. Thanks for the contribution!
