### ISSUE TITLE
ofxDynamixel

### ISSUE THREAD

**Issue by ghiouar** [atduskgreg/ofxaddons.com#165]
Hi,
I created an addon for controlling and interacting with Dynamixel Robotis Actuator. please find it here :
https://github.com/ghiouar/ofxDynamixel

It is based on DynamixelSDK library from ROBOTIS (manufacturer of the Dynamixel Actuator). I would like put it in the Hardware Interface category.

Thanks!
Ghiouar

**Comment by jamezilla** [comment]
All set, thanks for contributing!
