### ISSUE TITLE
ofxKuKinectV2 addon

### ISSUE THREAD

**Issue by perevalovds** [atduskgreg/ofxaddons.com#171]
Hi! We made an addon for KinectV2 (using in Windows), which is compilation of ofxKinectV2 and ofxMultiKinectV2, plus simple working in Windows (simple installation using Project Generator).
We developed it for our own project, but sure it will be useful for wide audience.
https://github.com/kuflex/ofxKuKinectV2

**Comment by jamezilla** [comment]
Categorized. Thanks! And sorry it took so long to get to this.
