### ISSUE TITLE
ofxGrafica

### ISSUE THREAD

**Issue by jagracar** [atduskgreg/ofxaddons.com#174]
Hi,

I would like to include my new addon in the foxaddons web.

I should be quite stable now and it comes with several examples that should work for linux, windows and mac:

https://github.com/jagracar/ofxGrafica

The addon categories that probably fit better are: Utilities and graphics

Thank you for your help!

**Comment by jamezilla** [comment]
All set! Thanks for your contribution.

**Comment by jagracar** [comment]
Thanks!
