### ISSUE TITLE
Procfile

### ISSUE THREAD

**Issue by edap** [atduskgreg/ofxaddons.com#181]
Is there any reason why the Procfile is not included in the repository?

I need to create it and to add it as content
web: bundle exec rails server -p 5000

Otherwise foreman throws an error

If, I can make a PR adding this

**Comment by jamezilla** [comment]
Apologies, the readme is out of date. We're no longer using a procfile because the stack isn't running on Heroku anymore.

The procfile was deleted in this commit: https://github.com/atduskgreg/ofxaddons.com/commit/7098075741975392bf31cb877eac602ad0918d9e#diff-5bd6b85c2d6fc987875f4bf82de2a15a

**Comment by jamezilla** [comment]
Reopening as a reminder to myself to clean up heroku related junk in the readme.
