### ISSUE TITLE
rails r 'Importer.run' exits immediately, nothing is scraped

### ISSUE THREAD

**Issue by jedahan** [atduskgreg/ofxaddons.com#183]
Hey when I try running `rails r 'Importer.run'` nothing gets logged to **logs/development.log** and the db is empty.

**Comment by jedahan** [comment]
If I try `bundle exec rails r 'Importer.run'` I get 
```
/Users/micro/.gems/gems/railties-4.2.10/lib/rails/commands/runner.rb:62:in `<top (required)>': undefined method `run' for Importer:Class (NoMethodError)
```

**Comment by jedahan** [comment]
I had to do
`bundle exec ./bin/rails r 'Importer.new.run'`

**Comment by jedahan** [comment]
Which hit the github api rate limit even though I have a client_id and _secret defined

**Comment by jamezilla** [comment]
Sorry, I'm sure it's frustrating to work with outdated docs. I will fix them up.

You can see how the job is run by `whenever` here:
https://github.com/atduskgreg/ofxaddons.com/blob/master/config/schedule.rb
