### ISSUE TITLE
ofxHelios

### ISSUE THREAD

**Issue by timredfern** [atduskgreg/ofxaddons.com#192]
Is ofxaddons still "scanning github daily"?

https://github.com/timredfern/ofxHelios is an addon to control the Helios open laser DAC.

It passes CI etc.

**Comment by jamezilla** [comment]
It is still scanning daily, but there's not much activity in the sorting/categorizing. What categories do you suggest? "Hardware Interface"?

Your addon was categorized by someone as "incomplete" so it was hidden. I question the value of the "incomplete" addon type - it's caused more problems than it's solved. I'll probably nuke that type...

**Comment by timredfern** [comment]
Thanks. Yep hardware interface probably makes sense although I'm going to add a mapping engine. Maybe this should be seperate though.

**Comment by jamezilla** [comment]
All set!
