### ISSUE TITLE
many of my addons are not listed

### ISSUE THREAD

**Issue by npisanti** [atduskgreg/ofxaddons.com#195]
Hello people, thanks for the great work on mantaining ofxaddons.com. 
I don't know why but maybe your parser for the addons don't like me, many of my things (some of them are around for weeks) are not in the list

adddon ---> category : 

https://github.com/npisanti/ofxAudioFile ---> sound
https://github.com/npisanti/ofxLaunchControllers ---> hardware interface 
https://github.com/npisanti/ofxFixture ---> hardware interface
https://github.com/npisanti/ofxClayblocks ---> hardware interface
https://github.com/npisanti/ofxDotFrag ---> graphics

**Comment by jamezilla** [comment]
There's not really anyone around categorizing things these days so many addons are languishing in the "unsorted" tab, or were hidden by the "incomplete" tag (which should probably just die).

I added some tags to your repos so they should show up correctly now. Thanks for contributing!

**Comment by npisanti** [comment]
thanks you!
