### ISSUE TITLE
Improved arcore addon : ofxARCore2

### ISSUE THREAD

**Issue by boehm-e** [atduskgreg/ofxaddons.com#196]
Hi , I made a new wrapper to use ARCore with openframeworks : ofxARCore2
This is an improved version of ofxARCore, I added : 
- Point cloud
- Augmented Images
- Hit testing
- Planes

This addon doesn't seems to appear on ofxAddons so I create this issue :)

https://github.com/boehm-e/ofxARCore2

**Comment by boehm-e** [comment]
up

**Comment by jamezilla** [comment]
Added to the graphics category. Any other suggested categories?
