### ISSUE TITLE
addon would not be added on the page

### ISSUE THREAD

**Issue by hiroyuki** [atduskgreg/ofxaddons.com#198]
Hi,

https://github.com/P-A-N/ofxLibRealSense2P

This addon is not listed in ofxAddons.com.
It has many unique features which are not in the original addon [ofxLibRealSense2](https://github.com/shiyamon/ofxLibRealSense2)

Should we do some work for it?

Thanks,

**Comment by jamezilla** [comment]
Added, thanks for contributing!
