### ISSUE TITLE
Please add my addon ofxWord2Vec to the list

### ISSUE THREAD

**Issue by perevalovds** [atduskgreg/ofxaddons.com#199]
Hi! I made pure C++ implementation of word2vec algorithm,
which is faster than ofxMSAWord2Vec,
and shipped with ready-to-use example.
Please, include it to Machine Learning category.
https://github.com/perevalovds/ofxWord2Vec

regards,
Denis Perevalov

**Comment by jamezilla** [comment]
Done. Thanks for contributing!
