### ISSUE TITLE
ofxWFC3D | new Addon

### ISSUE THREAD

**Issue by action-script** [atduskgreg/ofxaddons.com#200]
Wave Function Collapse 3D
https://github.com/action-script/ofxWFC3D

**Comment by action-script** [comment]
Any update into this? The addon is not appearing at the ofxaddons site

**Comment by jamezilla** [comment]
@action-script please suggest which categories you'd like to add this addon to.

**Comment by jamezilla** [comment]
Added to `graphics` and `algorithms` - let me know if that works for you.
