### ISSUE TITLE
ofxPytorch addon

### ISSUE THREAD

**Issue by perevalovds** [atduskgreg/ofxaddons.com#201]
Hi, I created ofxPytorch addon which allows to create realtime C++ applications uses Pytorch in openFrameworks. It's longwaited addon, so I hope it will be useful for others.

Currently it supports openFrameworks 0.10.1, Windows, Visual Studio 2017 C++, CPU.

https://github.com/perevalovds/ofxPytorch

**Comment by jamezilla** [comment]
Added to the machine learning category.
