### ISSUE TITLE
My addon wasnt added to the website 

### ISSUE THREAD

**Issue by CharStiles** [atduskgreg/ofxaddons.com#210]
Is there something I should do differently? The website says that addons are added as long as they have the ofx prefix.
Category: Graphics
Description: This addon for playing large sequences of point cloud PLY files back real-time.
Here is the addon: https://github.com/CharStiles/ofxPlySequence
Thank you :)

**Comment by montoyamoraga** [comment]
hey @CharStiles i just contributed my first ofx addon, and i found yours and mine here in "unsorted"
https://ofxaddons.com/unsorted
and i think to be added to "categories" we need to ask for that transfer over here in issues, still not sure how the process is

**Comment by moebiussurfing** [comment]
hey, I see that very often my Github ofxAddons are not listing neither.

Then it seems that we are missing some addons that are not listed, 
ie: when we check weekly https://ofxaddons.com/freshest.
On the web it says that nothing has to be done:

> You don't have to! Uploading it to Github is enough, as long as you have the 'ofx' prefix in your repository name then we'll find it. Feel free to file an issue on Github if you want to tell us about it and let us know what category it belongs in.

Any idea if I am missing something or maybe the ofxAddons searcher is missing addons?
How do I submit my addon to this page?
Could be related to the absence of addon_config.mk file sometimes?

**Comment by jamezilla** [comment]
@CharStiles added this to the graphics category.

@moebiussurfing @montoyamoraga Apologies your addons aren't being categorized. I basically have zero time to dedicate to this site these days.
