### ISSUE TITLE
delete my addon's link with old name, and add category

### ISSUE THREAD

**Issue by montoyamoraga** [atduskgreg/ofxaddons.com#211]
hi!
my addon is called ofxOpenDrawingMachine, 
https://github.com/montoyamoraga/ofxOpenDrawingMachine
i first created the repo as "ofxDrawingMachine" and it is still indexed in unsorted, can this old one be deleted?
also, can mine be moved from "unsorted" to the category "Hardware interface"?
thanks :)

**Comment by jamezilla** [comment]
Done.
