### ISSUE TITLE
Addon are not added to ofxaddons.com

### ISSUE THREAD

**Issue by dasoe** [atduskgreg/ofxaddons.com#213]
Hi all,

Thanks for your awesome work. As my addons are not added to the page, I thought I might tell you about 2 of them:

Category: GUI (Not sure, you think so, too?)
Description: Integration of Ultralight Browser, focus on ease of use, early stage, though.
Here is the addon: https://github.com/dasoe/ofxUltralight

Category: Utilities
Description: Simple integration of basic Project Settings based on XML. Logging and auto-save included.
Here is the addon: https://github.com/dasoe/ofxXmlBasedProjectSettings

thanks and have a great day!
oe

**Comment by jamezilla** [comment]
Done.
