### ISSUE TITLE
ofxHLuv

### ISSUE THREAD

**Issue by PauRosello97** [atduskgreg/ofxaddons.com#215]
Here's a new graphics addon:

ofxHLuv is an implementation of HLuv for OpenFrameworks. HLuv is a perceptually uniform color space with a constant luminance.

**link:** https://github.com/PauRosello97/ofxHLuv

**Comment by jamezilla** [comment]
Any category suggestions?

**Comment by PauRosello97** [comment]
Graphics

**Comment by jamezilla** [comment]
Done
