### ISSUE TITLE
ofxGCode

### ISSUE THREAD

**Issue by andymasteroffish** [atduskgreg/ofxaddons.com#218]
Hi all,

I just released a library called ofxGCode for creating G-code to be used with plotters.

https://github.com/andymasteroffish/ofxGCode

I'm making a post here because I made the repo about a year ago and it may be have been scraped and (reasonably) dismissed. It really wasn't ready for prime-time until this week.

Not sure if the category would be Utilities or Hardware Interface

**Comment by jamezilla** [comment]
Added to both categories.
