### ISSUE TITLE
ofxFontSampler addon

### ISSUE THREAD

**Issue by tcoppex** [atduskgreg/ofxaddons.com#219]
Hi,

This is a _**Typgraphy**_ addons to evaluate and tesselate simple glyphes.
https://github.com/tcoppex/ofxFontSampler

It depends on an other addon, [ofxTriangleMesh](https://github.com/tcoppex/ofxTriangleMesh), which is a forked improvement of the original one [probably ***Graphics*** or ***Algorithms***].

Thanks.

**Comment by jamezilla** [comment]
Done
