### ISSUE TITLE
Regarding adding my addon to the page

### ISSUE THREAD

**Issue by YiJongIn** [atduskgreg/ofxaddons.com#221]
Hello!

While I reorganizing my recent work, I found a repository of ofxAddon I made a few years ago.
And I figured it would be nice to share it with folks in of community!
Could you please add my addon to the ofxAddons.com?
It's called FuturisticUI which visualizes data in a futuristic design.

https://github.com/YiJongIn/ofxFuturisticUI

Thanks so much!

Jong-in

**Comment by jamezilla** [comment]
Sorry this has languished for so long. Added to the GUI category.
