### ISSUE TITLE
New addons: ofxDaisySP and ofxDStudio

### ISSUE THREAD

**Issue by StaffanMelin** [atduskgreg/ofxaddons.com#227]
https://github.com/StaffanMelin/ofxDaisySP
Description:
An addon that together with ofxDStudio can be used to create music with openFrameworks: make a studio with code!

https://github.com/StaffanMelin/ofxDStudio
Description:
An addon that together with ofxDaisySP can be used to create music with openFrameworks: make a studio with code!
DStudio provides another abstraction layer where you don't deal with soundstreams and filters but with synthesizers, mixers, plugins and sequencers.

Category: Sound

Both have thumbnails in the root of the repos.

Thank you!

**Comment by jamezilla** [comment]
Done. Thanks for contributing!

**Comment by StaffanMelin** [comment]
@jamezilla, can't find it on

https://ofxaddons.com/categories/5-sound

Is there something more I must do to make it work?

**Comment by jamezilla** [comment]
Apologies. Not sure why the categories didn't stick. I believe this is resolved now.

**Comment by StaffanMelin** [comment]
No need to apologize @jamezilla! It works now! :)

Thank you for your work!
